# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  # Email address of administrator that will get exception notifications
  # and requests for assistance from users:
  administrator_email: <%= ENV['ADMINISTRATOR_EMAIL'] %>
  # Secret key used to encrypt the discount code:
  discount_code_salt: <%= ENV['DISCOUNT_CODE_SALT'] %>

development:
  <<: *default
  secret_key_base: af13bb24e94fb4edb10dc6638865c55c35c41acd71aaffb8b1bf723b31a663dc745ec5431ed10ab439f4403c5553a1adfcf0fce3f12e40d5fa7a301b995d34b3

test:
  <<: *default
  secret_key_base: caa89e4cd3af4994ff1af5548a16af63352b93d10b63401304ec96b88369395352253c879261d1010ba75dfe753082073cccf2d0534362638e04c5d2f7064684

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
